[package]
name = "dsp"
version = "0.1.0"
authors = ["Robert Jördens <rj@quartiq.de>"]
edition = "2018"

[dependencies]
libm = "0.2.1"
serde = { version = "1.0", features = ["derive"], default-features = false }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "cossin"
harness = false

[features]
nightly = []
